### ISSUE TITLE
Error if system exists but body does not in EDSM

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/Canonn-EDSM-Updater#29]
While validating reports, there are cases where a system may exist in EDSM but the body does not, the report to site script is failing due to a null body value.

```
Processing "new" report ID:22 by CMDR Nemac
----------------------------------------------
Prechecking validity...
Validating Report:

{ id: '22',
  cmdrName: 'Nemac',
  clientVersion: 'EDMC-Canonn.1.9.1',
  userType: 'pc',
  reportType: 'new',
  reportStatus: 'pending',
  systemName: 'Dumboe XE-R d4-2357',
  bodyName: 'Dumboe XE-R d4-2357 4 a',
  latitude: 32.594208,
  longitude: 136.131775,
  type: 'Bark Mound' }

 - [PASS] "type" OK
 - [PASS] CMDR is in CAPI
 - [PASS] CMDR is not blacklisted
 - [PASS] Client is not blacklisted
 - [SKIP] System not in CAPI

<- Fetching [systems] from EDSM.
<- Fetching [bodies] from EDSM.

 - [PASS] System exists in EDSM.

Precheck complete. Report is VALID.

Checking and updating missing data
----------------------------------------------
 [MISS] Adding system:  Dumboe XE-R d4-2357
<- Updating [systems] in CAPI
        Field "systemName" is different. Source: "undefined" | Value: "DUMBOE XE-R D4-2357"
        Field "edsmID" is different. Source: "undefined" | Value: "36602202"
        Field "id64" is different. Source: "undefined" | Value: "80994283557419"
        Field "edsmCoordLocked" is different. Source: "undefined" | Value: "false"
        Field "edsmCoordX" is different. Source: "undefined" | Value: "-9998.28125"
        Field "edsmCoordY" is different. Source: "undefined" | Value: "-1.78125"
        Field "edsmCoordZ" is different. Source: "undefined" | Value: "22428.59375"
 [MISS] Adding body:  undefined
<- Updating [bodies] in CAPI
(node:26786) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toUpperCase' of undefined
    at system_from_edsm (/nixstorage/Github/capi/CAPIv2-Updater/build/updaters/body_from_edsm.js:21:33)
    at updateSingle (/nixstorage/Github/capi/CAPIv2-Updater/build/api/canonn/canonn.js:170:17)
    at /nixstorage/Github/capi/CAPIv2-Updater/build/api/canonn/canonn.js:93:5
    at new Promise (<anonymous>)
    at updateCAPIData (/nixstorage/Github/capi/CAPIv2-Updater/build/api/canonn/canonn.js:92:10)
    at CAPI_update (/nixstorage/Github/capi/CAPIv2-Updater/build/api/api.js:85:48)
    at /nixstorage/Github/capi/CAPIv2-Updater/build/scripts/reports/site_from_report.js:144:50
(node:26786) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26786) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![image](https://user-images.githubusercontent.com/8593673/55291193-b47d0900-5390-11e9-89d1-af2e3412c89b.png)

**Comment by derrickmehaffy** [comment]
It would appear the follow is not being ran due to there being no bodies at all: https://github.com/canonn-science/CAPIv2-Updater/blob/9a8a7ee709c465c1dec059b9c989430220675581/src/validators/report.js#L216-L220

**Comment by derrickmehaffy** [comment]
fixed
